twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        store: '@App\Service\StoreConfig'
        cart_manager: '@App\Service\CartManager'
        category_repository: '@App\Repository\CategoryRepository'

when@test:
    twig:
        strict_variables: true
